language: python
python:
  - "3.6"

services:
  - postgresql

env:
  - DJANGO=1.9.1

install:
  - pip install -r requirements.txt

before_script:
  - psql -c "CREATE DATABASE hashtagbrews;" -U postgres
  - psql -c "CREATE USER mee PASSWORD 'password';" -U postgres
  - psql -c "ALTER USER mee CREATEDB;" -U postgres
  - psql -c "GRANT ALL PRIVILEGES on DATABASE database to mee;" -U postgres

script:
  - python manage.py migrate
  - python manage.py test
