language: python
python:
  - "3.6"

env:
  - SECRET_KEY='TEST'
services:
  - postgresql

install:
  - pip install -r requirements.txt

script:
  - python manage.py migrate
  - python manage.py test

deploy:
  provider: heroku
  api_key:
    secure: 12354487-fe77-4d39-bf16-e1903e02a9fc
  app: stocksrunsbackend
  on:
    repo: ugwumadu116/stock_runs_backend

