version: "3"
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ".:/api"
    ports:
      - "8000:8000"
    depends_on:
      - migration
  migration:
    build: .
    command: python manage.py migrate --noinput
    volumes:
      - ".:/api"
