# Generated by Django 2.2.7 on 2019-11-22 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockstore',
            name='date2',
            field=models.DateField(auto_now=True),
        ),
    ]
