# Generated by Django 2.2.7 on 2019-11-22 12:01

from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_remove_stockstore_date2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockstore',
            old_name='value_currency',
            new_name='model_currency',
        ),
        migrations.AddField(
            model_name='stockstore',
            name='model',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='NGN', max_digits=60, null=True),
        ),
        migrations.AlterField(
            model_name='stockstore',
            name='value',
            field=models.IntegerField(null=True),
        ),
    ]
