# Generated by Django 2.2.7 on 2019-11-22 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_stockstore_date2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockstore',
            name='date2',
        ),
    ]
