# Generated by Django 2.2.7 on 2019-11-22 12:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_auto_20191122_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockstore',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
